export const democracyMessages = [
  "Democracy does not wait. Move.",
  "Freedom advances only when you do.",
  "Hesitation is not a strategy.",
  "Order requires action.",
  "Liberty favors the decisive.",
  "Stand firm. Execute.",
  "Delay serves no cause.",
  "Discipline is loyalty in motion.",
  "Advance with conviction.",
  "The mission moves. So do you.",
  "Resolve over comfort.",
  "Strength is proven through action.",
  "Victory respects commitment.",
  "Duty first. Doubt later.",
  "Act with authority.",
  "Progress demands engagement.",
  "Hold the line. Then push forward.",
  "Purpose leaves no room for inertia.",
  "Commit. Advance. Conclude.",
  "History remembers the ones who moved.",
  "For order. Act.",
  "Democracy advances through you.",
  "Your hesitation aids the enemy.",
  "Stand ready. Execute cleanly.",
  "Conviction is your greatest weapon.",
  "Freedom requires participation.",
  "Advance without apology.",
  "Strength is service in action.",
  "Resolve defines the outcome.",
  "Move as if it matters. It does."
]